spring.application.name=auth-service
spring.cloud.config.uri=http://localhost:8080
spring.config.import=optional:configserver:http://localhost:8080

# Local fallback values used when service-config is not running yet
# or when cloud-conf has not been pushed to GitHub.
server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8081/eureka/
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:postgresql://localhost:5433/auth_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info

security.jwt.secret=banking-project-inf462-development-secret-key-please-change-before-production
security.jwt.expiration-ms=86400000
