server:
  port: 8087

spring:
  application:
    name: service-loan
  cloud:
    config:
      uri: http://localhost:8080
  config:
    import: optional:configserver:http://localhost:8080

  datasource:
    url: jdbc:postgresql://localhost:5433/loan_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

external:
  service:
    account-url: http://localhost:8082
    customer-url: http://localhost:8085
    notification-url: http://localhost:8088
    transaction-url: http://localhost:8086
    ai-url: http://localhost:5000

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
