spring.application.name=service-registry
spring.cloud.config.uri=http://localhost:8080
spring.config.import=optional:configserver:

server.port=8081

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8081/eureka/
eureka.instance.hostname=localhost
spring.cloud.inetutils.default-hostname=localhost
spring.cloud.inetutils.default-ip-address=127.0.0.1

management.endpoints.web.exposure.include=health,info
