server.port=8086

spring.cloud.config.enabled=false

# Connect using your active Docker port 5433
spring.datasource.url=jdbc:postgresql://localhost:5433/transaction_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- ADD THESE TWO LINES TO DISABLE EUREKA ---
eureka.client.enabled=false
eureka.client.register-with-eureka=false