server.port=8085

spring.cloud.config.enabled=false

# Connect using your active Docker port 5433
spring.datasource.url=jdbc:postgresql://localhost:5433/transaction_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- ADD THESE TWO LINES TO DISABLE EUREKA ---
eureka.client.enabled=false
eureka.client.register-with-eureka=false

external.service.account-url=http://localhost:8082
external.service.notification-url=http://localhost:8087
external.service.auth-url=http://localhost:8084
management.endpoints.web.exposure.include=health,info
