spring.application.name=transaction-service
# On active explicitement le profil par défaut pour correspondre à la recherche du serveur
spring.profiles.active=default

# On indique à l'application d'aller chercher tout le reste sur le serveur centralisé
spring.config.import=optional:configserver:http://localhost:8080