events {}

http {

    upstream customer_backend {

        least_conn;

        server customer1:8085;
        server customer2:8085;
        server customer3:8085;
    }

    server {

        listen 80;

        location /customers/ {

            proxy_pass http://customer_backend;
        }
    }
}